CREATE TABLE APPS.XXCM_FA_ASSETS_NEW
(
  NUMERO_DE_ACTIVO        NUMBER,
  LIBRO                   VARCHAR2(200 ),
  ETIQUETA                VARCHAR2(200 ),
  DESCRIPCION             VARCHAR2(200 ),
  MODELO                  VARCHAR2(200 ),
  NUMERO_DE_SERIE         VARCHAR2(200 ),
  FECHA_DE_DEPOSITO       DATE,
  VALOR_FIJO_1            VARCHAR2(200 ),
  VALOR_FIJO_2            VARCHAR2(200 ),
  ESTATUS                 VARCHAR2(200 ),
  MENSAJE                 VARCHAR2(2000 ),
  FECHA_DE_PROCESAMIENTO  DATE
);